# Generated by Django 4.0.5 on 2022-07-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
